# Generated by Django 5.2 on 2026-01-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
